### ISSUE TITLE
No contact method and typos

### ISSUE THREAD

**Issue by PHPGangsta** [WebTigers/Tiger#2]
Hello,

I wanted to contact you, but neither on your website nor on the Amazon Marketplace page nor on Github I can find an email address or contact form. That's why I'm writing here.

Some hints regarding your website/project:

1. https://webtigers.com/de
Notice: The language 'de' has to be added before it can be used. in /var/www/tiger-vendor/vendor/shardj/zf1-future/library/Zend/Translate/Adapter.php on line 445
Notice: No translation for the language 'de' available. in /var/www/tiger-vendor/vendor/shardj/zf1-future/library/Zend/Translate/Adapter.php on line 458
-> display_errors is On.. A bad idea on production systems. There are internal paths visible, and maybe also parameters, mysql-username and password, and so on. You should disable display_errors on production systems.

2. http://webtigers.com/
unencrypted website without HTTPS redirect.

3. No chance to contact you anywhere. Please put contact information somewhere, a contact form, an imprint or similar.

4. Typos on your Amazon marketplace page:
- "Apache 2.4 and PFM": Maybe you mean "PHP-FPM"?
- "FZ1-Future" should be "ZF1-Future" I guess?

Thanks!

**Comment by WebTigers** [comment]
@PHPGangsta, thank you for the notes. Updates have been made. Thanks again!
